import { useMemo } from 'react';
import ReactECharts from 'echarts-for-react';
import { useBlotterStore } from '../store/useBlotterStore';
import { enhanceChartOption } from '../utils/chartEnhancement';

/**
 * AI Graph Panel - displays ECharts visualization generated by the AI.
 * Renders in the main 3/4 overlay area when AI returns a chartOption.
 */
export function AIGraphPanel() {
  const aiChartOption = useBlotterStore((s) => s.aiChartOption);

  const option = useMemo(() => {
    if (!aiChartOption || typeof aiChartOption !== 'object') {
      return null;
    }
    return enhanceChartOption(aiChartOption as Record<string, unknown>);
  }, [aiChartOption]);

  if (!option) {
    return (
      <div className="ai-graph-panel ai-graph-empty">
        <p>No chart data. Run an AI Data Query that returns a chart (e.g. &quot;chart notional by product&quot;).</p>
      </div>
    );
  }

  return (
    <div className="ai-graph-panel">
      <ReactECharts
        option={option}
        style={{ height: '100%', minHeight: 300 }}
        opts={{ renderer: 'canvas' }}
        notMerge
      />
    </div>
  );
}
